# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_auto_20170207_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='parentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='depot.Dossier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.Dossier'),
        ),
    ]
