# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_auto_20170216_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nicename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
