# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0004_document_nicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='nicename',
        ),
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
