# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170216_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['mot_en']},
        ),
    ]
