# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom, Initiale, Chaque nom est s\xe9par\xe9 par un point virgule', max_length=250, verbose_name='Auteurs')),
                ('annee', models.CharField(max_length=4, verbose_name='Ann\xe9e publication')),
                ('resume', models.TextField()),
                ('articlefile', models.FileField(upload_to='DocsReferences', verbose_name='Article analys\xe9')),
                ('origine', models.TextField(blank=True, null=True, verbose_name='Syntaxe de recherche')),
                ('typeetudetxt', models.TextField(blank=True, null=True, verbose_name='D\xe9tails type \xe9tude')),
                ('typeparticipanttxt', models.TextField(blank=True, null=True, verbose_name='D\xe9tails participants')),
                ('comparaisontxt', models.TextField(blank=True, null=True, verbose_name='Description du groupe de comparaison')),
                ('interceptiontxt', models.TextField(blank=True, null=True, verbose_name="D\xe9tails niveau d'interceptions")),
                ('interventiontxt', models.TextField(blank=True, null=True, verbose_name='Description du programme')),
                ('mesuresresultats', models.TextField(blank=True, help_text='Arrestation, traitement / r\xe9f\xe9rence, r\xe9cidive, incarc\xe9ration ... ', null=True, verbose_name='R\xe9sultat mesur\xe9s par')),
                ('analyses', models.TextField(blank=True, help_text='Descriptives\xa0: d\xe9tails; Quali\xa0: th\xe8mes ', null=True, verbose_name='R\xe9sultats des analyses')),
                ('region', models.CharField(blank=True, help_text='Province du QC, Canada, Autre pays (pr\xe9ciser) ... ', max_length=250, null=True, verbose_name='\xc9tendue g\xe9ographique')),
                ('autresinfos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Autres informations')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssistantScoping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Niveau d'interception")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Originebd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="BD o\xf9 l'article a \xe9t\xe9 trouv\xe9")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Typeetude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Type d'\xe9tude, m\xe9thode")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Typeparticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Type de participants')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Typepub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Type d'\xe9tude / publication")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='interception',
            field=models.ManyToManyField(to='scopingreview.Interception'),
        ),
        migrations.AddField(
            model_name='article',
            name='originebd',
            field=models.ManyToManyField(to='scopingreview.Originebd'),
        ),
        migrations.AddField(
            model_name='article',
            name='typeetude',
            field=models.ManyToManyField(to='scopingreview.Typeetude'),
        ),
        migrations.AddField(
            model_name='article',
            name='typeparticipant',
            field=models.ManyToManyField(to='scopingreview.Typeparticipant'),
        ),
        migrations.AddField(
            model_name='article',
            name='typepub',
            field=models.ManyToManyField(to='scopingreview.Typepub'),
        ),
    ]
