# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopingreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titre',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='autresinfos',
            field=models.TextField(blank=True, null=True, verbose_name='Autres informations'),
        ),
        migrations.AlterField(
            model_name='article',
            name='interception',
            field=models.ManyToManyField(to='scopingreview.Interception', verbose_name="Niveau d'interception"),
        ),
        migrations.AlterField(
            model_name='article',
            name='originebd',
            field=models.ManyToManyField(to='scopingreview.Originebd', verbose_name="BD o\xf9 l'article a \xe9t\xe9 trouv\xe9"),
        ),
        migrations.AlterField(
            model_name='article',
            name='typeetude',
            field=models.ManyToManyField(to='scopingreview.Typeetude', verbose_name="Type d'\xe9tude, m\xe9thode"),
        ),
        migrations.AlterField(
            model_name='article',
            name='typeparticipant',
            field=models.ManyToManyField(to='scopingreview.Typeparticipant', verbose_name='Type de participants'),
        ),
        migrations.AlterField(
            model_name='article',
            name='typepub',
            field=models.ManyToManyField(to='scopingreview.Typepub', verbose_name="Type d'\xe9tude / publication"),
        ),
    ]
