# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('courriel', models.CharField(blank=True, max_length=200)),
                ('domaine', models.CharField(blank=True, max_length=250)),
                ('envoifait', models.DateField(blank=True)),
                ('reponse', models.CharField(blank=True, max_length=250)),
                ('responsable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
