# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('acronyme', models.CharField(blank=True, max_length=50, null=True)),
                ('depuis', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptif', models.TextField()),
                ('domaine', models.CharField(blank=True, max_length=250, null=True)),
                ('siteweb', models.CharField(blank=True, max_length=250, null=True)),
                ('courriel', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=250, null=True)),
                ('motsclef', models.CharField(blank=True, max_length=250, null=True)),
                ('autresinfos', models.CharField(blank=True, max_length=250, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
