# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='popcible',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
