# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottin', '0003_ressource_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='DocsRessources/'),
        ),
    ]
