# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottin', '0004_auto_20170608_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='DocsRessources')),
            ],
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='docfile',
        ),
        migrations.AlterField(
            model_name='ressource',
            name='motsclef',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Mots Clefs'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='popcible',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Population cible'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='document',
            field=models.ManyToManyField(blank=True, default='', to='bottin.Document', verbose_name='Document associe'),
        ),
    ]
