# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottin', '0006_auto_20170608_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='ressource',
        ),
        migrations.AddField(
            model_name='ressource',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='DocsRessources', verbose_name='Documentation utile'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
