# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bottin', '0007_auto_20170608_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='DocsRessources', verbose_name='Documentation utile')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssistantDocument', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='documentation',
        ),
        migrations.AlterField(
            model_name='ressource',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssistantRessource', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='autresinfos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Autres informations'),
        ),
        migrations.AddField(
            model_name='document',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottin.Ressource'),
        ),
    ]
