# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottin', '0008_auto_20170608_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Br\xe8ve description'),
        ),
    ]
