# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPhil', '0004_auto_20170212_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='mot_en',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
