# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogPhil', '0005_auto_20170216_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entree',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='mot_en',
            field=models.CharField(error_messages={'unique': 'Ce mot clef existe d\xe9j\xe0'}, max_length=100, unique=True),
        ),
    ]
